langauge: minimal

env:
  global:
     - HOMEBREW_NO_AUTO_UPDATE=1
     - BREW_FISH2="https://raw.githubusercontent.com/Homebrew/homebrew-core/2827b020c3366ea93566a344167ba62388c16c7d/Formula/fish.rb"

script:
    - curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisherman
    - fish -c "fisher fishtape .; fishtape tests/*.fish"

jobs:
  include:
    - stage: test
      name: "Fish 2.X Linux"
      os: linux
      sudo: required
      install:
       - sudo apt-add-repository -y ppa:fish-shell/release-2
       - sudo apt-get update
       - sudo apt-get install -y fish

    - stage: test
      name: "Fish 2.X macOS"
      os: osx
      install: brew install $BREW_FISH2

    - stage: test
      name: "Fish 3.X Linux"
      os: linux
      sudo: required
      install:
       - sudo apt-add-repository -y ppa:fish-shell/release-3
       - sudo apt-get update
       - sudo apt-get install -y fish

    - stage: test
      name: "Fish 3.X macOS"
      os: osx
      install: brew install fish

    - stage: deploy
      language: node_js
      node_js: stable
      provider: script
      skip_cleanup: true
      script: npx semantic-release
